"""add codeforces profiles submissions and contest results tables

Revision ID: 8c4e4afc408c
Revises: 3f9126fe6724
Create Date: 2026-06-30 07:20:14.276828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4e4afc408c'
down_revision: Union[str, None] = '3f9126fe6724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codeforces_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('max_rank', sa.String(length=50), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codeforces_profiles_handle'), 'codeforces_profiles', ['handle'], unique=False)
    op.create_index(op.f('ix_codeforces_profiles_id'), 'codeforces_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_codeforces_profiles_user_id'), 'codeforces_profiles', ['user_id'], unique=True)
    op.create_table('codeforces_contest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('contest_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('old_rating', sa.Integer(), nullable=False),
    sa.Column('new_rating', sa.Integer(), nullable=False),
    sa.Column('rating_update_time_seconds', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['codeforces_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codeforces_contest_results_contest_id'), 'codeforces_contest_results', ['contest_id'], unique=False)
    op.create_index(op.f('ix_codeforces_contest_results_id'), 'codeforces_contest_results', ['id'], unique=False)
    op.create_index(op.f('ix_codeforces_contest_results_profile_id'), 'codeforces_contest_results', ['profile_id'], unique=False)
    op.create_table('codeforces_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('codeforces_submission_id', sa.BigInteger(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('problem_index', sa.String(length=10), nullable=False),
    sa.Column('problem_name', sa.String(length=255), nullable=False),
    sa.Column('problem_rating', sa.Integer(), nullable=True),
    sa.Column('programming_language', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=True),
    sa.Column('passed_test_count', sa.Integer(), nullable=False),
    sa.Column('time_consumed_millis', sa.Integer(), nullable=False),
    sa.Column('memory_consumed_bytes', sa.Integer(), nullable=False),
    sa.Column('creation_time_seconds', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['codeforces_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codeforces_submissions_codeforces_submission_id'), 'codeforces_submissions', ['codeforces_submission_id'], unique=False)
    op.create_index(op.f('ix_codeforces_submissions_id'), 'codeforces_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_codeforces_submissions_profile_id'), 'codeforces_submissions', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codeforces_submissions_profile_id'), table_name='codeforces_submissions')
    op.drop_index(op.f('ix_codeforces_submissions_id'), table_name='codeforces_submissions')
    op.drop_index(op.f('ix_codeforces_submissions_codeforces_submission_id'), table_name='codeforces_submissions')
    op.drop_table('codeforces_submissions')
    op.drop_index(op.f('ix_codeforces_contest_results_profile_id'), table_name='codeforces_contest_results')
    op.drop_index(op.f('ix_codeforces_contest_results_id'), table_name='codeforces_contest_results')
    op.drop_index(op.f('ix_codeforces_contest_results_contest_id'), table_name='codeforces_contest_results')
    op.drop_table('codeforces_contest_results')
    op.drop_index(op.f('ix_codeforces_profiles_user_id'), table_name='codeforces_profiles')
    op.drop_index(op.f('ix_codeforces_profiles_id'), table_name='codeforces_profiles')
    op.drop_index(op.f('ix_codeforces_profiles_handle'), table_name='codeforces_profiles')
    op.drop_table('codeforces_profiles')
    # ### end Alembic commands ###
